MyPrecios/MyPrecios/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('users/', include('users.urls',namespace='users')),
    path('__debug__/', include('debug_toolbar.urls')),

]

MyPrecios/pages/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.urls import include, path
from rest_framework import routers

from .views import  MailsViewSet


class MyCustomRouter(routers.SimpleRouter):
   routes = [
      routers.Route(url=r'^{prefix}$',
                    mapping={'get': 'list'},
                    name='{basename}-list',
                    detail=False,
                    initkwargs={'suffix': 'List'}),
      routers.Route(url=r'^{prefix}/{lookup}$',
                    mapping={'get': 'retrieve'},
                    name='{basename}-detail',
                    detail=True,
                    initkwargs={'suffix': 'Detail'})
   ]

router = routers.SimpleRouter()
router.register(r'mails', MailsViewSet,basename='ails')


urlpatterns = [
   path('', include(router.urls))
]

MyPrecios/users/urls.py
from django.contrib.auth.views import LogoutView
from django.views.decorators.cache import cache_page
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
   path('login/', cache_page(60)(views.LoginUser.as_view()), name='login'),
   path('logout/', views.logout_user, name='logout'),
   path('register/', views.RegisterUser.as_view(), name='register'),

]

MyPrecios/pages/models.py
from django.db import models


class Mails(models.Model):
    from_user =models.CharField(max_length=50,blank=True)
    to_user = models.CharField(max_length=50,blank=True)
    message = models.TextField(blank=True,)
    sent_at = models.DateTimeField(auto_now=True)
    is_draft = models.BooleanField(default=False)

MyPrecios/users/models.py
from django.db import models

# Create your models here.

MyPrecios/pages/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.deconstruct import deconstructible

from pages.models import Mails

# @deconstructible
# class UserValidator:
#     allowed_names = User.objects.all().values_list('username', flat=True)
#     code = 'users'
#
#     def __init__(self, name = None):
#         self.name = name if name else 'enter something'
#
#     def __call__(self, name):
#         if not self.name in self.allowed_names:
#             raise ValidationError(self.name, code=self.code)


class SendMessageForm(forms.ModelForm):
    class Meta:
        model = Mails
        fields = [ 'to_user', 'message' ]
        widgets = {
            'to_user': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 50, 'rows': 5}),
        }
#доп валидации поверх is_valid
    def clean_to_user(self):
        to_user = self.cleaned_data['to_user']
        users = User.objects.all().values_list('username', flat=True)
        if to_user not in users:
            raise ValidationError('there is no user with this username')
        return to_user

class CreateDraftForm(SendMessageForm):
    pass

MyPrecios/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from pages.models import Mails


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label="Логин",
                    widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label="Пароль",
                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')

class CreateUserForm(UserCreationForm):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    class Meta:
        nodel = get_user_model()
        fields = ('username', 'password1', 'password2')

MyPrecios/pages/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DeleteView, TemplateView, ListView, FormView, DetailView
from django.db.models import Q
from pages.models import Mails
from .forms import SendMessageForm, CreateDraftForm


class MainPage(LoginRequiredMixin, ListView):
    model = Mails
    template_name = 'pages/main_page.html'
    context_object_name = 'mails'
    def get_queryset(self):
        return Mails.objects.filter(Q(to_user=self.request.user.username) & Q(is_draft=False))

class OutcomeMessages(MainPage):
    extra_context = {'bool':True}
    def get_queryset(self):
        return  Mails.objects.filter(Q(from_user=self.request.user.username) & Q(is_draft=False))

class SendMessage(LoginRequiredMixin,FormView):
    form_class = SendMessageForm
    template_name = 'pages/sendform.html'
    success_url = reverse_lazy("home")

#вызывается после метода is_valid
    def form_valid(self, form):
        form.instance.from_user = self.request.user.username
        form.save()
        return super().form_valid(form)

class ShowDraft(MainPage):
    template_name = 'pages/drafts.html'
    def get_queryset(self):
        return Mails.objects.filter(Q(from_user=self.request.user.username) & Q(is_draft=True))

class CreateDraft(LoginRequiredMixin,FormView):
    form_class = CreateDraftForm
    template_name = 'pages/drafts_form.html'
    success_url = reverse_lazy("drafts")

    def form_valid(self, form):
        form.instance.from_user = self.request.user.username
        form.instance.is_draft = True
        form.save()
        return super().form_valid(form)

class EditDraft(LoginRequiredMixin,UpdateView):
    model = Mails
    template_name = 'pages/drafts_form.html'
    fields = ['to_user', 'message' , 'is_draft']
    success_url = reverse_lazy("drafts")

class ShowMessage(LoginRequiredMixin,DetailView):
    model = Mails
    template_name = 'pages/show_message.html'
    slug_url_kwarg = 'message_id'
    context_object_name = 'message'

    def get_object(self):
        return get_object_or_404(Mails,id=self.kwargs['message_id'])

MyPrecios/users/views.py
from mailbox import Message

from django.contrib.auth import get_user_model, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template.defaultfilters import title
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView

from users.forms import LoginUserForm,  CreateUserForm


class LoginUser(LoginView):
    model = User
    form_class = LoginUserForm
    template_name = 'users/login.html'

class RegisterUser(CreateView):
    form_class = UserCreationForm
    model = User
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

MyPrecios/pages/templates/pages/drafts.html
{% extends 'base.html' %}
{% block messages %}
<main>
        <section>
            <form action="{% url 'createdraft' %}" method="GET">
    <button type="submit">Написать черновик</button>
</form>
        </section>
        <section>
            <h3>Последние черновики</h3>
            <ul>
                {% for mail in mails %}
                    <li>
                        <strong>To:</strong> {{ mail.to_user }}<br>
                        <strong>Message:</strong> {{ mail.message|truncatechars:25 }}
                       <p><button onclick="location.href='editdraft/{{ mail.id }}';">Перейти в черновик</button></p>
<!--                        <li><a href="{% url 'editdraft' mail.id  %}">редактировать</a></li>-->

                    </li>
                {% endfor %}


            </ul>
        </section>
    </main>
{% endblock messages %}

MyPrecios/pages/templates/pages/drafts_form.html
{% extends 'base.html' %}

{% block messages %}

<h1>{{title}}</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">сохранить</button></p>
</form>
{% endblock %}

MyPrecios/pages/templates/pages/home_page.html
{% load static %}
<link type="text/css" href="{% static 'pages/css/home_page.css' %}" rel="stylesheet" />
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Почтовый сервис</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Добро пожаловать в Почтовый сервис</h1>
        <nav>
            <ul>
                <li><a href="">Вход</a></li>
                <li><a href="/register">Регистрация</a></li>
                <li><a href="/contacts">Контакты</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <section>
            <h2>Вход в систему</h2>
            <form action="#" method="post">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
                <label for="password">Пароль:</label>
                <input type="password" id="password" name="password" required>
                <button type="submit">Войти</button>
            </form>
        </section>
    </main>
    <footer>
        <p>© 2024 Почтовый сервис. Все права защищены.</p>
    </footer>
</body>
</html>

MyPrecios/pages/templates/pages/main_page.html
{% extends 'base.html' %}
{% block messages %}
<main>
        <section>
            <form action="{% url 'send' %}" method="GET">
    <button type="submit">Написать письмо</button>
</form>
        </section>
        <section>
            <h3>Последние сообщения</h3>
            <ul>
                {% for mail in mails %}
                    <li>
                        {% if bool %}
                        <strong>To:</strong> {{ mail.to_user }}<br>
                         {% else %}
                        <strong>From:</strong> {{ mail.from_user }}<br>
                        {% endif %}
                        <strong>Message:</strong> {{ mail.message|truncatechars:25 }}
                         <p><button onclick="location.href='message/{{ mail.id }}';">Перейти к сообщению</button></p>

                    </li>
                {% endfor %}


            </ul>
        </section>
    </main>
{% endblock messages %}

MyPrecios/pages/templates/pages/register_page.html
{% load static %}
<link type="text/css" href="{% static 'pages/css/register_page.css' %}" rel="stylesheet" />
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <header>
        <h1>Регистрация в Почтовом сервисе</h1>
        <nav>
            <ul>
                <li><a href="">Главная</a></li>
                <li><a href="">Вход</a></li>
                <li><a href="">Контакты</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <section>
            <h2>Создать учетную запись</h2>
            <form action="#" method="post">
                <label for="email">Email:</label>
                <input type="email" id="email" name="email" required>
                <label for="password">Пароль:</label>
                <input type="password" id="password" name="password" required>
                <label for="password-repeat">Повторите пароль:</label>
                <input type="password" id="password-repeat" name="password-repeat" required>
                <button type="submit">Регистрация</button>
            </form>
        </section>
    </main>
    <footer>
        <p>© 2024 Почтовый сервис. Все права защищены.</p>
    </footer>
</body>
</html>

MyPrecios/pages/templates/pages/sendform.html
{% extends 'base.html' %}

{% block messages %}

<h1>{{title}}</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Отправить</button></p>
</form>
{% endblock %}

MyPrecios/pages/templates/pages/show_message.html
{% extends 'base.html' %}
{% block messages %}
<main>
        <section>
            <p> Сообщение от {{ message.from_user }}</p>
           {{message.message|linebreaks}}
        </section>
    </main>
{% endblock messages %}

MyPrecios/templates/base.html
{% load static %}
<link type="text/css" href="{% static 'pages/css/main_page.css' %}" rel="stylesheet" />
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
</head>
<body>
    <header>
        <h1>Почтовый сервис</h1>
        <nav>
            <ul>
                {% if request.user.is_authenticated %}
                <li><a href="/">Входящие</a></li>
                <li><a href="{% url 'outcome' %}">Отправленные</a></li>
                <li><a href="{% url 'drafts' %}">Черновики</a></li>
                <li><a href="{% url 'drafts_cache' %}">Кэш</a></li>
                <li><a href="{% url 'users:logout' %}">Выход</a></li>
                {% else %}
                <li><a href="{% url 'users:register' %}">Регистрация</a></li>
                {% endif %}

            </ul>
        </nav>
    </header>
    {% block messages %}

    {% endblock messages %}
    <footer>
        <p>© 2024 Почтовый сервис. Все права защищены.</p>
    </footer>
</body>
</html>

MyPrecios/users/templates/users/login.html
{% extends 'base.html' %}

{% block messages %}
<h1>Авторизация</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Войти</button></p>
</form>
{% endblock %}

MyPrecios/users/templates/users/register.html
{% extends 'base.html' %}

{% block messages %}
<h1>register</h1>

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Регистрация</button></p>
</form>
{% endblock %}